### ISSUE TITLE
help_crack ssl certificate error

### ISSUE THREAD

**Issue by Czechball** [RealEnder/dwpa#77]
Hey,
When trying to run help_crack recently, I got the following error:
```
Couldn't submit key
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Sleeping...
Couldn't submit key
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Sleeping...
```
My OS is Windows 10 21H1 build ``19043.1237``, Python version ``Python 3.9.7``, help-crack version ``1.1.1``.

Any ideas?

**Comment by RealEnder** [comment]
Hi, this is result from certificate expiration: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
Removed the old root not to be sent by the server, please check again, now should be working fine.

**Comment by Czechball** [comment]
Sadly still the same error. Maybe I need to clear some sort of cache or update my cert store?

**Comment by RealEnder** [comment]
There is no cache involved, try to update root certificates.

**Comment by LowSkillDeveloper** [comment]
Same
![image](https://user-images.githubusercontent.com/25121341/135758329-9ff9cf25-45fa-48a6-ae86-f818e2faf3cc.png)

**Comment by RealEnder** [comment]
The expired certificate is the one, that was cross-signed root of LE.
Don't have windows machine to reproduce (assume this is the platform?).
The active LE certs are here: https://letsencrypt.org/certificates/
wpa-sec.stanev.org is issued by the operative RA cert, which is signed by ISRG Root X1. So you'll need to install ISRG Root X1.

**Comment by Czechball** [comment]
Today I tried running help_crack again and the issue has been resolved. I'm not sure how and why, but I don't get the certificate errors anymore. I haven't done anything regarding certificates or certificate store on my desktop so I'm gonna asume something somewhere has been updated. I'm gonna leave this issue open for other people with the problem and until a solution is found.

**Comment by RealEnder** [comment]
Great! For sure the root certificates were updated. Some more information on the issue:
https://letsencrypt.org/2021/10/01/cert-chaining-help.html
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

**Comment by YankoNach** [comment]
The same... Just under Windows:
```
Couldn't submit key
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
Sleeping...
```
Windows 10 Pro; ver. 21H2 - 19044.1348
Python version:
`Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32`
help_crack version:
`PS J:\kali\AlexStanev> py .\help_crack.py -v
J:\kali\AlexStanev\help_crack.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import StrictVersion
1.1.1`

**Comment by YankoNach** [comment]
> The same... Just under Windows:
> 
> ```
> Couldn't submit key
> Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
> Sleeping...
> ```
> 
> Windows 10 Pro; ver. 21H2 - 19044.1348 Python version: `Python 3.10.0 (tags/v3.10.0:b494f59, Oct 4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32` help_crack version: `PS J:\kali\AlexStanev> py .\help_crack.py -v J:\kali\AlexStanev\help_crack.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives from distutils.version import StrictVersion 1.1.1`

Well, now it's working fine!
I'm complete newbie in Python (and in programing in general), but my explanation is that running:
`py -v` 
resulted in updating the certificates by "certifi_win32" site package...

**Comment by RealEnder** [comment]
Great this worked! I still see an issue with server configuration, but will have a chanse to fix it in couple of days.

**Comment by YankoNach** [comment]
Well, again stop working?!?
And strange, the best hash speed is under Linux Mint 20.2 Uma, Cinnamon 5.0.7, hashcat v6.2.3:
Speed.#1.........:   425.8 kH/s (310.71ms) @ Accel:16 Loops:1024 Thr:1024 Vec:1
Under Windows 10 with latest hashcat - well under 250 kH/s
Under Kali - again about 300 kH/s...
Hardware is the same:
Machine:   Type: Desktop Mobo: MSI model: Z270 SLI PLUS (MS-7A59) v: 1.0 serial: <filter> 
           UEFI: American Megatrends v: 1.A0 date: 06/30/2018 
CPU:       Topology: Quad Core model: Intel Core i7-6700K bits: 64 type: MT MCP arch: Skylake-S 
           rev: 3 L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 63999 
           Speed: 4200 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 4200 2: 4200 3: 4201 
           4: 4198 5: 4200 6: 4200 7: 4201 8: 4200 
Graphics:  Device-1: NVIDIA TU106 [GeForce RTX 2060 SUPER] vendor: Micro-Star MSI driver: nvidia 
           v: 470.82.00 bus ID: 01:00.0 chip ID: 10de:1f06 
           Display: x11 server: X.Org 1.20.11 driver: nvidia resolution: 2560x1440~144Hz 
           OpenGL: renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA 470.82.00 
           direct render: Yes

**Comment by RealEnder** [comment]
Did some heavy reconfiguration, please check again.

**Comment by RealEnder** [comment]
These are probably timeout issues - eventually help_crack.py will continue.
Closing this as TLS issues have to be solved long time ago.
